### ISSUE TITLE
I can't compile the libbson.dll

### ISSUE THREAD

**Issue by CapDev12** [Sovos-Compliance/libbson-build#1]
Use MongoDB in Delphi XE5

I want to use NewBson(json: UTF8String)
but I can not compile libbson.dll
have only Visual Studio 2010 Express

Сan you upload libbson.dll  fow win32 ?

thanks in advance

**Comment by jsbattig** [comment]
What kind of problem you have?

Only piece hard-coded that could cause a problem is on the
build_internal.cmd script:

call "C:\Program Files (x86)\Microsoft Visual Studio
10.0\VC\bin\vcvars32.bat"
msbuild ..\msvc\libbson.sln "/p:Configuration=%1;Platform=%2

The path to Visual studio. You can easily change that and try to compile.

Sebastian

**Comment by CapDev12** [comment]
not found bson-config.h

I rename   bson-config.h.in

1>d:\work\mongodb\cc-mongo-delphi-driver\libbson-build__submodules\libbson\src\bson\bson-config.h(32): error C2018: неизвестный знак "0x40"

in line
#if BSON_HAVE_STDBOOL_H != 1

and 25 such errors

**Comment by jsbattig** [comment]
Have you properly initialized the submodule libbson-build-headers?

the following files are present there:

.gitignoreInitial commita month ago
README.mdInitial commita month ago
bson-config.hB-0 Added new cmake generated files in their own submodulea month ago
bson-stdint.hB-0 Added new cmake generated files in their own submodulea month ago
bson-version.hB-0 Added new cmake generated files in their own submodule
a month ag

you can’t just rename the .in file from libbson. That’s a template file used by cmake to generate the target file used as part of the build process.

The repo you are using contains working files, some of them slightly tuned from the files generated by cmake.

Also, you need to use the build.cmd from build subfolder in root of libbson-build repo.

I don’t know of any incompatibilities with VS 2010 express. The writer of the library tries to keep it as compatible as possible, with different compilers and platforms. That’s why he tries to follows C89 standard rather than newer C standards available.

Check on the highlighted things above and let me know if you still have trouble.

Sent from Windows Mail

From: SunFrost
Sent: ‎Friday‎, ‎April‎ ‎25‎, ‎2014 ‎6‎:‎46‎ ‎PM
To: Convey-Compliance/libbson-build
Cc: jsbattig

not found bson-config.h

I rename bson-config.h.in

1>d:\work\mongodb\cc-mongo-delphi-driver\libbson-build__submodules\libbson\src\bson\bson-config.h(32): error C2018: неизвестный знак "0x40"

in line
#if BSON_HAVE_STDBOOL_H != 1

and 25 such errors

**Comment by CapDev12** [comment]
I copy files in libbson-build-headers
nothing has changed, the same mistakes

I spent the same two days
I have no more time to deal with compilation 
could you just upload the compiled libbson.dll 32-bit ?

thanks in advance !

**Comment by jsbattig** [comment]
I can’t upload to repo the binaries, we don’t provide binaries for Libbson neither we want to pollute our repos with binaries.

Please understand I’m not the writer of the main libbson repo. We just created this libbson-build repo as a shortcut for people who don’t want to use cmake and need to quickly compile in Windows.

If you clone the main libbson-build repo and properly initialize the submodules, you don’t need to copy any files around or anything like that.

Just open the command line, go to \Build folder on the root of the repo, and execute build.cmd.

If you have compilation issues, it might be something local to your environment.

If you create a repo yourself, and give me rights to push, I can do the favor of pushing our current version, but I strongly recommend you figure out how to compile the sources. This project is on Alpha status, the developer is updating the code constantly, so the binaries must be kept up to speed and I can’t keep a repo in GitHub synchronized with our binaries (besides, it’s not recommended to use binaries within Git).

Finally, when requesting help from other developers in the open source community, I recommend you to tone down your approach. People “donate” the product of their time and work to the community, so we don’t expect users of this donated work to project a sense of entitlement somehow that everything should work for them our of the box. The attitude is rather trying to figure our what’s going on, and if there’s an issue, you contribute back not with a plain problem, but with a set of ideas or possible solutions showing you did your homework to try to figure out what’s wrong. That’s how the open source community best operates.

Best regards and good luck.

Sent from Windows Mail

From: SunFrost
Sent: ‎Saturday‎, ‎April‎ ‎26‎, ‎2014 ‎5‎:‎07‎ ‎AM
To: Convey-Compliance/libbson-build
Cc: jsbattig

I copy files in libbson-build-headers

nothing has changed, the same mistakes

I spent the same two days
I have no more time to deal with compilation 
could you just upload the compiled libbson.dll 32-bit ?

thanks in advance !

**Comment by CapDev12** [comment]
Yes you are right, I apologize for the tone.

"If you clone the main libbson-build repo and properly initialize the submodules, you don’t need to copy any files around or anything like that.

Just open the command line, go to \Build folder on the root of the repo, and execute build.cmd."

c1 : fatal error C1083: Can not open source file: ..__submodules\libbson\src\yajl\yajl_version.c: No such file or directory [D:\Work\MongoDB
\CC-mongo-delphi-driver\libbson-build\msvc\libbson.vcxproj]
  yajl_tree.c
...

**Comment by jsbattig** [comment]
Did you retrieve all files in submodule?

You need to initialize submodules and pull contents.

**Comment by CapDev12** [comment]
git.exe submodule update --init

Cloning into '__submodules/libbson'...
Unable to use key file "D:\Soft\Putty\id_rsa.ppk" (SSH-1 private key)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:Convey-Compliance/libbson.git' into submodule path '__submodules/libbson' failed

**Comment by CapDev12** [comment]
version.rc(10): fatal error RC1015: cannot open include file 'afxres.h'. [D:\Work\MongoDB\CC-mongo-delphi-driver\libbson-build\msvc\libbson.vcxproj]

**Comment by jsbattig** [comment]
You need to register your ssh key within GitHub in order to be able to pull
with ssh.

**Comment by CapDev12** [comment]
gen and add SSH
update __submodules

 version.rc(10): fatal error RC1015: cannot open include file 'afxres.h'. [D:\Work\MongoDB\CC-mongo-delphi-driver\libbson-build\msvc\libbson.vcxproj]

**Comment by CapDev12** [comment]
I found the solution:
"This header is a part of the MFC Library. VS Express edition doesn't contain MFC. If your project doesn't use MFC you can safely replace afxres.h with windows.h"
http://stackoverflow.com/questions/3566018/cannot-open-include-file-afxres-h-in-vc2010-express

And build libbson_d32_v0-6-8.dll !! 
Cheers is a victory !
Sebastian thank you, for help and patience !

**Comment by jsbattig** [comment]
That's great!
I will update the repo with that change, great catch.
We always try to keep these type of libraries "lowest common denominator"
compatible.
